import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const appJs = readFileSync(new URL('../public/app.js', import.meta.url), 'utf8');
const css = readFileSync(new URL('../public/styles.css', import.meta.url), 'utf8');
const serverJs = readFileSync(new URL('../src/server.js', import.meta.url), 'utf8');
const operationsJs = readFileSync(new URL('../src/operations.js', import.meta.url), 'utf8');

test('frontend exposes required runtime configuration features', () => {
  assert.match(appJs, /appCategory/);
  assert.match(appJs, /card-menu/);
  assert.match(appJs, /clickable-card/);
  assert.match(appJs, /查询条件/);
  assert.match(appJs, /searchFields/);
  assert.match(appJs, /columnWidths/);
  assert.match(appJs, /index-cell/);
  assert.match(appJs, /序号/);
  assert.match(appJs, /renderResizableHeader/);
  assert.match(appJs, /startColumnResize/);
  assert.match(appJs, /resize-edge/);
  assert.match(appJs, /sticky-action-cell/);
  assert.match(appJs, /作为搜索条件/);
  assert.match(appJs, /renderAssistantDrawer/);
  assert.match(appJs, /AI 助理/);
  assert.match(appJs, /currentRoute/);
  assert.match(appJs, /writeRoute/);
  assert.match(appJs, /URLSearchParams/);
  assert.match(appJs, /createAppFromPrompt/);
  assert.match(appJs, /AI 助理/);
  assert.match(appJs, /saveAppMetadata/);
  assert.match(appJs, /topbar-app-info/);
  assert.match(appJs, /inlineEditableText/);
  assert.match(appJs, /字段设置/);
  assert.match(appJs, /表单视图/);
  assert.match(appJs, /ondblclick/);
  assert.match(appJs, /editable-cell/);
  assert.match(appJs, /selected-cell/);
  assert.match(appJs, /clickedOutsideTableSelection/);
  assert.match(appJs, /pointerdown', \(event\) =>/);
  assert.match(appJs, /renderImageValue/);
  assert.match(appJs, /image-thumb/);
  assert.match(appJs, /openImagePreview/);
  assert.match(appJs, /renderFileValue/);
  assert.match(appJs, /cell-link/);
  assert.match(appJs, /uploads/);
  assert.match(appJs, /startCellEdit/);
  assert.match(appJs, /importTableData/);
  assert.match(appJs, /startCellRangeSelection/);
  assert.match(appJs, /copySelectedCellsToClipboard/);
  assert.match(appJs, /copySelectedCellsAsImage/);
  assert.match(appJs, /isMultiCellMatrix/);
  assert.match(appJs, /if \(isMultiCellMatrix\(matrix\)\) showCellCopyToolbar\(\)/);
  assert.match(appJs, /finally \{\n    hideCellCopyToolbar\(\);/);
  assert.match(appJs, /pasteCellsFromClipboard/);
  assert.match(appJs, /pasteCellMatrix/);
  assert.match(appJs, /fieldTypesCompatible/);
  assert.match(appJs, /clipboardPayloadFromText/);
  assert.match(appJs, /复制区域是 \$\{sourceRows\} 行 \$\{sourceCols\} 列/);
  assert.doesNotMatch(appJs, /finishCellRangeSelection[\s\S]{0,260}copySelectedCellsToClipboard/);
  assert.doesNotMatch(appJs, /finishCellRangeSelection[\s\S]{0,220}showCellCopyToolbar/);
  assert.match(appJs, /selection-top/);
  assert.match(appJs, /selection-bottom/);
  assert.match(appJs, /selection-left/);
  assert.match(appJs, /selection-right/);
  assert.match(appJs, /ClipboardItem/);
  assert.match(appJs, /compositionstart/);
  assert.match(appJs, /compositionend/);
  assert.match(appJs, /event\.isComposing/);
  assert.match(appJs, /text: '编辑'/);
  assert.match(appJs, /draggable/);
  assert.doesNotMatch(appJs, /page-drag-handle/);
  assert.doesNotMatch(appJs, /chart: '图'|dashboard: '板'|editor: '编'/);
  assert.match(appJs, /pageNavKind/);
  assert.match(appJs, /navKind: 'page'/);
  assert.match(appJs, /buildBlankPage/);
  assert.match(appJs, /renderBlankPage/);
  assert.match(appJs, /inferPageCardsFromPrompt/);
  assert.match(appJs, /startPageCardResize/);
  assert.match(operationsJs, /navKind: 'table'/);
  assert.match(css, /\.page-type-icon\.table/);
  assert.match(css, /\.blank-page-canvas/);
  assert.match(css, /\.page-card-canvas/);
  assert.match(appJs, /一行 \$\{value\} 列/);
  assert.match(appJs, /getViews/);
  assert.match(appJs, /renderViewBar/);
  assert.match(appJs, /renderViewMenu/);
  assert.match(appJs, /新建视图/);
  assert.match(appJs, /openFilterModal/);
  assert.match(appJs, /不包含/);
  assert.match(appJs, /thisWeek/);
  assert.match(appJs, /thisMonth/);
  assert.match(appJs, /openSortModal/);
  assert.match(appJs, /openGroupModal/);
  assert.match(appJs, /groupRecords/);
  assert.match(appJs, /summarizeCurrentView/);
  assert.match(appJs, /设计当前表单/);
  assert.match(appJs, /designCurrentForm/);
  assert.match(appJs, /getFormDesign/);
  assert.match(appJs, /topbar-app-info/);
  assert.match(appJs, /inlineEditableText/);
  assert.match(appJs, /export\.xlsx/);
  assert.match(appJs, /openHeaderContextMenu/);
  assert.match(appJs, /openFieldEditModal/);
  assert.match(appJs, /fieldPatchFromEditor/);
  assert.match(appJs, /下拉选项/);
  assert.match(appJs, /数字格式/);
  assert.match(appJs, /日期格式/);
  assert.match(appJs, /duplicateField/);
  assert.match(appJs, /insertField/);
  assert.match(appJs, /隐藏字段/);
  assert.match(appJs, /向右插入列/);
  assert.match(appJs, /表单视图/);
  assert.match(appJs, /unused-list/);
  assert.doesNotMatch(appJs, /current\.field === field\.id && current\.direction/);
  assert.doesNotMatch(appJs, /\balert\(/);
  assert.doesNotMatch(appJs, /\bconfirm\(/);
  assert.doesNotMatch(appJs, /\bprompt\(/);
  assert.match(appJs, /openConfirmDialog/);
  assert.match(appJs, /quickAddRecord/);
  assert.match(appJs, /bulkDeleteRecords/);
  assert.match(appJs, /clearCurrentViewConfig/);
  assert.match(appJs, /renderSummaryRow/);
  assert.match(appJs, /renderNumericSummary/);
  assert.match(appJs, /summary-group-row/);
  assert.match(appJs, /快速新增行/);
  assert.match(appJs, /批量删除/);
  assert.match(appJs, /清除视图/);
  assert.match(appJs, /renderAiPlanCard/);
  assert.match(appJs, /loadAssistantHistory/);
  assert.match(appJs, /startNewAssistantSession/);
  assert.match(appJs, /assistantMessagesFromSession/);
  assert.match(appJs, /requestAiPlan/);
  assert.match(appJs, /executeAiPlan/);
  assert.match(appJs, /确认执行/);
  assert.match(appJs, /document\.addEventListener\('paste'/);
  assert.match(appJs, /relation-options/);
  assert.match(appJs, /targetEntity/);
  assert.match(appJs, /displayField/);
  assert.match(appJs, /renderSelectTag/);
  assert.match(appJs, /relationFieldDisplayText/);
  assert.match(appJs, /selectedCellImageRows/);
  assert.match(appJs, /cellImageContent/);
  assert.match(appJs, /querySelectorAll\('\.select-tag, \.relation-tag'\)/);
  assert.match(appJs, /drawCellImageContent/);
  assert.match(appJs, /drawRoundedRect/);
  assert.match(appJs, /Math\.max\(3, window\.devicePixelRatio \|\| 1\)/);
  assert.match(appJs, /context\.scale\(pixelRatio, pixelRatio\)/);
  assert.doesNotMatch(appJs, /label \|\| '未选择'/);
  assert.match(appJs, /openCreateTableModal/);
  assert.match(appJs, /新建表/);
  assert.match(appJs, /deleteField/);
  assert.match(appJs, /loadCurrentPageRecords/);
  assert.match(appJs, /pageEntityForRecordLoad/);
  assert.match(appJs, /await loadCurrentPageRecords\(\);\n  const page = body\.app\.ui\.pages/);
  assert.match(appJs, /async function quickAddRecord[\s\S]*await loadCurrentPageRecords\(\);/);
  assert.doesNotMatch(appJs, /document\.querySelectorAll\('\\.cell-editing'\)\.forEach/);
});

test('frontend has styles for list config, form layout, inline edit, and logs', () => {
  assert.match(css, /\.hero-meta/);
  assert.match(css, /\.section-heading/);
  assert.match(css, /\.category-filter/);
  assert.match(css, /\.clickable-card/);
  assert.match(css, /\.card-menu/);
  assert.match(css, /\.menu-item/);
  assert.match(css, /\.query-zone/);
  assert.match(css, /\.assistant-fab/);
  assert.match(css, /\.assistant-history-bar/);
  assert.match(css, /\.assistant-history-select/);
  assert.match(css, /\.drawer-backdrop/);
  assert.match(css, /\.table-wrap/);
  assert.match(css, /\.sticky-action-cell/);
  assert.match(css, /\.action-cell/);
  assert.match(css, /\.index-cell/);
  assert.match(css, /\.resizable-column/);
  assert.match(css, /\.resize-edge/);
  assert.match(css, /\.resizing-column/);
  assert.match(css, /\.sidebar-label/);
  assert.doesNotMatch(css, /\.page-drag-handle/);
  assert.match(css, /\.topbar-app-info/);
  assert.match(css, /\.inline-edit-text/);
  assert.match(css, /\.header-edit-input/);
  assert.match(css, /\.layout-row/);
  assert.match(css, /\.process-log/);
  assert.match(css, /\.check-row/);
  assert.match(css, /\.view-bar/);
  assert.match(css, /\.view-tab/);
  assert.match(css, /\.view-menu/);
  assert.match(css, /\.config-row/);
  assert.match(css, /\.group-row/);
  assert.match(css, /\.field-hint/);
  assert.match(css, /\.table-command-row/);
  assert.match(css, /\.quick-searches/);
  assert.match(css, /\.editable-cell/);
  assert.match(css, /\.selected-cell/);
  assert.match(css, /border-color: #b7cdf6/);
  assert.match(css, /\.editable-cell\.selected-cell\.selection-top/);
  assert.match(css, /\.cell-copy-toolbar/);
  assert.match(css, /\.image-thumb/);
  assert.match(css, /\.image-preview-full/);
  assert.match(css, /\.file-link/);
  assert.match(css, /\.cell-link/);
  assert.match(css, /\.summary-row/);
  assert.match(css, /\.numeric-summary/);
  assert.match(css, /\.summary-group-row/);
  assert.match(css, /\.context-menu/);
  assert.match(css, /\.layout-editor/);
  assert.match(css, /\.form-preview/);
  assert.match(css, /\.select-cell/);
  assert.match(css, /\.selection-label/);
  assert.match(css, /\.confirm-modal/);
  assert.match(css, /\.select-tag/);
  assert.match(css, /\.relation-tag/);
  assert.match(css, /\.ai-status-card/);
  assert.match(css, /\.ai-clarify-card/);
  assert.match(css, /\.ai-plan-card/);
  assert.match(css, /\.create-table-button/);
  assert.match(css, /\.context-menu-sep/);
});
