import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

const indexHtml = readFileSync(new URL('../public/index.html', import.meta.url), 'utf8');
const appShellJs = readFileSync(new URL('../public/app.js', import.meta.url), 'utf8');
const css = readFileSync(new URL('../public/styles.css', import.meta.url), 'utf8');
const assistantCss = readFileSync(new URL('../public/ai-assistant/style.css', import.meta.url), 'utf8');
const serverJs = readFileSync(new URL('../src/server.js', import.meta.url), 'utf8');
const runtimeRouteJs = readFileSync(new URL('../src/routes/runtime.js', import.meta.url), 'utf8');
const operationsJs = readFileSync(new URL('../src/services/operations.js', import.meta.url), 'utf8');
const assistantIndexJs = readFileSync(new URL('../public/ai-assistant/index.js', import.meta.url), 'utf8');
const assistantChatViewJs = readFileSync(new URL('../public/ai-assistant/ChatView.js', import.meta.url), 'utf8');
const assistantSSEClientJs = readFileSync(new URL('../public/ai-assistant/SSEClient.js', import.meta.url), 'utf8');
const assistantToolDisplayJs = readFileSync(new URL('../public/ai-assistant/ToolDisplay.js', import.meta.url), 'utf8');
const assistantStreamRendererJs = readFileSync(new URL('../public/ai-assistant/StreamRenderer.js', import.meta.url), 'utf8');
const commonDomJs = readFileSync(new URL('../public/common/dom.js', import.meta.url), 'utf8');
const commonApiJs = readFileSync(new URL('../public/common/api.js', import.meta.url), 'utf8');
const commonModalJs = readFileSync(new URL('../public/common/modal.js', import.meta.url), 'utf8');
const commonToastJs = readFileSync(new URL('../public/common/toast.js', import.meta.url), 'utf8');
const commonStorageJs = readFileSync(new URL('../public/common/storage.js', import.meta.url), 'utf8');
const homeIndexJs = readFileSync(new URL('../public/app-home/index.js', import.meta.url), 'utf8');
const homeAppCardJs = readFileSync(new URL('../public/app-home/AppCard.js', import.meta.url), 'utf8');
const homeImportModalJs = readFileSync(new URL('../public/app-home/ImportModal.js', import.meta.url), 'utf8');
const dataTableJs = readFileSync(new URL('../public/app-runtime/DataTable.js', import.meta.url), 'utf8');
const viewBarJs = readFileSync(new URL('../public/app-runtime/ViewBar.js', import.meta.url), 'utf8');
const tableHeaderJs = readFileSync(new URL('../public/app-runtime/TableHeader.js', import.meta.url), 'utf8');
const tableRowJs = readFileSync(new URL('../public/app-runtime/TableRow.js', import.meta.url), 'utf8');
const cellEditorJs = readFileSync(new URL('../public/app-runtime/CellEditor.js', import.meta.url), 'utf8');
const cellSelectionJs = readFileSync(new URL('../public/app-runtime/CellSelection.js', import.meta.url), 'utf8');
const fieldEditorJs = readFileSync(new URL('../public/app-runtime/FieldEditor.js', import.meta.url), 'utf8');
const recordModalJs = readFileSync(new URL('../public/app-runtime/RecordModal.js', import.meta.url), 'utf8');
const sidebarJs = readFileSync(new URL('../public/app-runtime/Sidebar.js', import.meta.url), 'utf8');
const runtimeIndexJs = readFileSync(new URL('../public/app-runtime/index.js', import.meta.url), 'utf8');
const runtimeFrameJs = readFileSync(new URL('../public/app-runtime/RuntimeFrame.js', import.meta.url), 'utf8');
const pageTypesJs = readFileSync(new URL('../public/app-runtime/PageTypes.js', import.meta.url), 'utf8');
const appJs = [
  appShellJs,
  commonDomJs,
  commonApiJs,
  commonModalJs,
  commonToastJs,
  commonStorageJs,
  dataTableJs,
  viewBarJs,
  tableHeaderJs,
  tableRowJs,
  cellEditorJs,
  cellSelectionJs,
  fieldEditorJs,
  recordModalJs,
  sidebarJs,
  runtimeIndexJs,
  runtimeFrameJs,
  pageTypesJs
].join('\n');

test('frontend exposes required runtime configuration features', () => {
  assert.match(indexHtml, /rel="icon" href="\/favicon\.ico" sizes="32x32"/);
  assert.equal(existsSync(new URL('../public/favicon.ico', import.meta.url)), true);
  assert.match(css, /\.brand-logo\s*\{[^}]*width:\s*32px;[^}]*height:\s*32px;/s);
  assert.match(homeAppCardJs, /export function appCategory/);
  assert.match(homeAppCardJs, /card-menu/);
  assert.match(homeAppCardJs, /clickable-card/);
  assert.match(viewBarJs, /searchFields/);
  assert.match(viewBarJs, /columnWidths/);
  assert.match(dataTableJs, /index-cell/);
  assert.match(dataTableJs, /序号/);
  assert.match(appJs, /renderResizableHeader/);
  assert.match(appJs, /startColumnResize/);
  assert.match(appJs, /resize-edge/);
  assert.match(dataTableJs, /sticky-action-cell/);
  assert.match(appJs, /作为搜索条件/);
  assert.match(appJs, /表格设置/);
  assert.match(appJs, /renderAssistantDrawer/);
  assert.match(appJs, /AI 助理/);
  assert.match(appJs, /classList\.contains\('modal-backdrop'\)/);
  assert.match(appJs, /\b(e|event)\.target\.remove\(\)/);
  assert.match(appJs, /import.*renderAssistantDrawer.*from.*ai-assistant/);
  assert.doesNotMatch(assistantIndexJs, /class: 'drawer-backdrop'/);
  assert.match(assistantIndexJs, /class: 'assistant drawer'/);
  assert.match(commonDomJs, /export function uiIcon/);
  assert.match(commonDomJs, /export function buttonLabel/);
  assert.match(appJs, /assistant-topbar-button/);
  assert.match(appJs, /state\.assistantOpen \? 'active' : ''/);
  assert.match(dataTableJs, /toolbar-action-group data-entry-group/);
  assert.match(dataTableJs, /toolbar-action-group data-mutation-group/);
  assert.match(dataTableJs, /toolbar-action-group view-rule-group/);
  assert.match(dataTableJs, /toolbar-action-group structure-config-group/);
  assert.match(dataTableJs, /toolbar-action-group view-rule-group/);
  assert.match(dataTableJs, /buttonLabel\('filter', '筛选'\)/);
  assert.match(appJs, /currentRoute/);
  assert.match(appJs, /writeRoute/);
  assert.match(appJs, /URLSearchParams/);
  assert.match(homeIndexJs, /export async function createAppFromPrompt/);
  assert.match(appJs, /AI 助理/);
  assert.match(appJs, /saveAppMetadata/);
  assert.match(appJs, /topbar-app-info/);
  assert.match(appJs, /inlineEditableText/);
  assert.match(dataTableJs, /表格设置/);
  assert.match(tableRowJs, /表单视图/);
  assert.match(appJs, /ondblclick/);
  assert.match(appJs, /editable-cell/);
  assert.match(appJs, /selected-cell/);
  assert.match(appJs, /clickedOutsideTableSelection/);
  assert.match(appJs, /pointerdown', \(event\) =>/);
  assert.match(appJs, /renderImageValue/);
  assert.match(appJs, /image-thumb/);
  assert.match(appJs, /openImagePreview/);
  assert.match(appJs, /renderFileValue/);
  assert.match(appJs, /cell-link/);
  assert.match(appJs, /uploads/);
  assert.match(appJs, /startCellEdit/);
  assert.match(dataTableJs, /importTableData/);
  assert.match(appJs, /startCellRangeSelection/);
  assert.match(appJs, /copySelectedCellsToClipboard/);
  assert.match(cellSelectionJs, /export function bindCellSelectionEvents/);
  assert.match(cellSelectionJs, /document\.addEventListener\('copy'/);
  assert.match(cellSelectionJs, /document\.addEventListener\('paste'/);
  assert.match(cellSelectionJs, /document\.addEventListener\('pointermove'/);
  assert.match(cellSelectionJs, /document\.addEventListener\('pointerup'/);
  assert.match(appShellJs, /bindCellSelectionEvents/);
  assert.match(appJs, /copySelectedCellsAsImage/);
  assert.match(appJs, /isMultiCellMatrix/);
  assert.match(appJs, /if \(isMultiCellMatrix\(matrix\)\) showCellCopyToolbar\(\)/);
  assert.match(appJs, /finally \{\n    hideCellCopyToolbar\(\);/);
  assert.match(appJs, /pasteCellsFromClipboard/);
  assert.match(appJs, /pasteCellMatrix/);
  assert.match(appJs, /fieldTypesCompatible/);
  assert.match(appJs, /clipboardPayloadFromText/);
  assert.match(appJs, /复制区域是 \$\{sourceRows\} 行 \$\{sourceCols\} 列/);
  assert.doesNotMatch(appJs, /finishCellRangeSelection[\s\S]{0,260}copySelectedCellsToClipboard/);
  assert.doesNotMatch(appJs, /finishCellRangeSelection[\s\S]{0,220}showCellCopyToolbar/);
  assert.match(appJs, /selection-top/);
  assert.match(appJs, /selection-bottom/);
  assert.match(appJs, /selection-left/);
  assert.match(appJs, /selection-right/);
  assert.match(appJs, /ClipboardItem/);
  assert.match(appJs, /compositionstart/);
  assert.match(appJs, /compositionend/);
  assert.match(appJs, /event\.isComposing/);
  assert.match(appJs, /text: '编辑'/);
  assert.match(appJs, /draggable/);
  assert.doesNotMatch(appJs, /page-drag-handle/);
  assert.doesNotMatch(appJs, /chart: '图'|dashboard: '板'|editor: '编'/);
  assert.match(appJs, /pageNavKind/);
  assert.match(appJs, /navKind: 'page'/);
  assert.match(appJs, /buildBlankPage/);
  assert.match(appJs, /renderBlankPage/);
  assert.match(css, /\.page-card-resize/);
  assert.match(operationsJs, /navKind: 'table'/);
  assert.match(css, /\.page-type-icon\.table/);
  assert.match(css, /\.blank-page-canvas/);
  assert.match(css, /\.page-card-canvas/);
  assert.match(appJs, /一行 \$\{value\} 列/);
  assert.match(viewBarJs, /getViews/);
  assert.match(viewBarJs, /renderViewBar/);
  assert.match(viewBarJs, /renderViewMenu/);
  assert.match(viewBarJs, /新建视图/);
  assert.match(viewBarJs, /openFilterModal/);
  assert.match(viewBarJs, /不包含/);
  assert.match(viewBarJs, /thisWeek/);
  assert.match(viewBarJs, /thisMonth/);
  assert.match(viewBarJs, /openSortModal/);
  assert.match(viewBarJs, /openGroupModal/);
  assert.match(dataTableJs, /groupRecords/);
  assert.match(appJs, /getFormDesign/);
  assert.match(appJs, /topbar-app-info/);
  assert.match(appJs, /inlineEditableText/);
  assert.match(dataTableJs, /export\.xlsx/);
  assert.match(appJs, /openHeaderContextMenu/);
  assert.match(appJs, /openFieldEditModal/);
  assert.match(appJs, /fieldPatchFromEditor/);
  assert.match(appJs, /下拉选项/);
  assert.match(appJs, /数字格式/);
  assert.match(appJs, /日期格式/);
  assert.match(appJs, /duplicateField/);
  assert.match(appJs, /insertField/);
  assert.match(appJs, /隐藏字段/);
  assert.match(appJs, /向右插入列/);
  assert.match(appJs, /表单视图/);
  assert.match(appJs, /unused-list/);
  assert.match(appJs, /class: 'form-grid form-preview'/);
  assert.match(appJs, /function renderFormFieldBlock/);
  assert.match(appJs, /form\.append\(renderFormFieldBlock\(field, input, design\)\)/);
  assert.match(appJs, /renderFormFieldBlock\(field, input, design, \{/);
  assert.match(appJs, /function disablePreviewInput/);
  assert.doesNotMatch(appJs, /current\.field === field\.id && current\.direction/);
  assert.doesNotMatch(appJs, /\balert\(/);
  assert.doesNotMatch(appJs, /\bconfirm\(/);
  assert.doesNotMatch(appJs, /\bprompt\(/);
  assert.match(appJs, /openConfirmDialog/);
  assert.match(appJs, /quickAddRecord/);
  assert.match(appJs, /bulkDeleteRecords/);
  assert.match(appJs, /clearCurrentViewConfig/);
  assert.match(appJs, /renderSummaryRow/);
  assert.match(appJs, /renderNumericSummary/);
  assert.match(dataTableJs, /summary-group-row/);
  assert.match(dataTableJs, /快速新增行/);
  assert.match(dataTableJs, /批量删除/);
  assert.match(appJs, /清除视图/);
  assert.match(assistantIndexJs, /SSEClient/);
  assert.match(assistantIndexJs, /renderAssistantDrawer/);
  assert.match(assistantChatViewJs, /class ChatView/);
  assert.match(assistantSSEClientJs, /class SSEClient/);
  assert.match(assistantToolDisplayJs, /class ToolDisplay/);
  assert.match(assistantStreamRendererJs, /class StreamRenderer/);
  assert.match(assistantIndexJs, /tool_confirm/);
  assert.match(appJs, /pasteCellsFromClipboard/);
  assert.match(runtimeRouteJs, /relation-options/);
  assert.match(appJs, /targetEntity/);
  assert.match(appJs, /displayField/);
  assert.match(appJs, /renderSelectTag/);
  assert.match(appJs, /relationFieldDisplayText/);
  assert.match(appJs, /selectedCellImageRows/);
  assert.match(appJs, /cellImageContent/);
  assert.match(appJs, /querySelectorAll\('\.select-tag, \.relation-tag'\)/);
  assert.match(appJs, /drawCellImageContent/);
  assert.match(appJs, /drawRoundedRect/);
  assert.match(appJs, /Math\.max\(3, window\.devicePixelRatio \|\| 1\)/);
  assert.match(appJs, /context\.scale\(pixelRatio, pixelRatio\)/);
  assert.doesNotMatch(appJs, /label \|\| '未选择'/);
  assert.match(appJs, /openCreateTableModal/);
  assert.match(appJs, /新建表/);
  assert.match(appJs, /deleteField/);
  assert.match(appJs, /loadCurrentPageRecords/);
  assert.match(appJs, /pageEntityForRecordLoad/);
  assert.match(appJs, /await loadCurrentPageRecords\(\);\n  const page = body\.app\.ui\.pages/);
  assert.match(appJs, /async function quickAddRecord[\s\S]*await loadCurrentPageRecords\(\);/);
  assert.doesNotMatch(appJs, /document\.querySelectorAll\('\\.cell-editing'\)\.forEach/);
  assert.match(commonDomJs, /export function h\(/);
  assert.match(commonApiJs, /export async function api\(/);
  assert.match(commonModalJs, /export function openConfirmDialog/);
  assert.match(commonToastJs, /export function toast\(/);
  assert.match(commonStorageJs, /export function readStorage/);
  assert.match(commonStorageJs, /export function writeStorage/);
  assert.match(commonStorageJs, /export function globalStorageKey/);
});

test('frontend has styles for list config, form layout, inline edit, and logs', () => {
  assert.match(css, /\.page-nav-item \.menu-item:hover,[\s\S]*?\.page-nav-item \.page-menu summary:hover[\s\S]*?background:\s*transparent/);
  assert.match(css, /\.hero-meta/);
  assert.match(css, /\.section-heading/);
  assert.match(css, /\.category-filter/);
  assert.match(css, /\.clickable-card/);
  assert.match(css, /\.card-menu/);
  assert.match(css, /\.card-menu-popover \.ghost-menu\.danger:hover,[\s\S]*background: #fef2f2/);
  assert.match(css, /\.card-menu summary:hover,[\s\S]*\.page-menu summary:hover,[\s\S]*\.view-menu-trigger:hover[\s\S]*background: #f1f5f9/);
  assert.match(css, /\.page-menu-popover \.ghost-menu\.danger:hover,[\s\S]*\.view-menu-popover \.ghost-menu\.danger-text:hover[\s\S]*background: #fef2f2/);
  assert.match(css, /\.menu-item/);
  assert.match(css, /\.query-zone/);
  assert.match(css, /\.assistant-fab/);
  assert.match(css, /\.icon-label-button/);
  assert.match(css, /\.ui-icon/);
  assert.match(css, /\.assistant-topbar-button\.active/);
  assert.match(css, /\.table-action-groups/);
  assert.match(css, /\.toolbar-action-group::after/);
  assert.match(css, /\.table-panel \.structure-config-group::after \{\n  display: block;/);
  assert.match(css, /\.export-menu summary \{\n  display: inline-flex;/);
  assert.match(assistantCss, /\.assistant-history-select/);
  assert.match(css, /\.drawer-backdrop/);
  assert.match(css, /\.table-wrap/);
  assert.match(css, /\.sticky-action-cell/);
  assert.match(css, /\.action-cell/);
  assert.match(css, /\.index-cell/);
  assert.match(css, /\.resizable-column/);
  assert.match(css, /\.resize-edge/);
  assert.match(css, /\.resizing-column/);
  assert.match(css, /\.sidebar-label/);
  assert.doesNotMatch(css, /\.page-drag-handle/);
  assert.match(css, /\.topbar-app-info/);
  assert.match(css, /\.inline-edit-text/);
  assert.match(css, /\.header-edit-input/);
  assert.match(css, /\.layout-row/);
  assert.match(css, /\.process-log/);
  assert.match(css, /\.check-row/);
  assert.match(css, /\.view-bar/);
  assert.match(css, /\.view-tab/);
  assert.doesNotMatch(css, /\.table-panel \.view-tab\.active::before/);
  assert.match(css, /\.view-menu/);
  assert.match(css, /\.config-row/);
  assert.match(css, /\.group-row/);
  assert.match(css, /\.field-hint/);
  assert.match(css, /\.table-command-row/);
  assert.match(css, /\.quick-searches/);
  assert.match(css, /\.editable-cell/);
  assert.match(css, /\.selected-cell/);
  assert.match(css, /border-color: #b7cdf6/);
  assert.match(css, /\.editable-cell\.selected-cell\.selection-top/);
  assert.match(css, /\.cell-copy-toolbar/);
  assert.match(css, /\.image-thumb/);
  assert.match(css, /\.image-preview-full/);
  assert.match(css, /\.file-link/);
  assert.match(css, /\.cell-link/);
  assert.match(css, /\.summary-row/);
  assert.match(css, /\.numeric-summary/);
  assert.match(css, /\.summary-group-row/);
  assert.match(css, /\.summary-cell:hover \.summary-mode-select/);
  assert.match(tableRowJs, /renderSummaryCell/);
  assert.match(tableRowJs, /summaryOptions\(field\)/);
  assert.match(dataTableJs, /listConfig\.summaries/);
  assert.match(css, /\.context-menu/);
  assert.match(css, /\.layout-editor/);
  assert.match(css, /\.form-preview/);
  assert.match(css, /\.field-label-row/);
  assert.doesNotMatch(css, /\.preview-head/);
  assert.doesNotMatch(css, /\.preview-input/);
  assert.match(css, /\.select-cell/);
  assert.match(css, /\.selection-label/);
  assert.match(css, /\.confirm-modal/);
  assert.match(css, /\.select-tag/);
  assert.match(css, /\.relation-tag/);
  assert.match(css, /\.ai-status-card/);
  assert.match(css, /\.ai-clarify-card/);
  assert.match(css, /\.ai-plan-card/);
  assert.match(css, /\.create-table-button/);
  assert.match(css, /\.context-menu-sep/);
  assert.match(css, /\.ghost-menu:hover \{[\s\S]*background: #e2e8f0/);
  assert.match(css, /tbody tr\.editable-row:hover td:not\(\.selected-cell\):not\(\.cell-editing\):not\(\.formula-error-cell\)[\s\S]*background: #f1f5f9/);
  assert.match(css, /\.compact-record-table tbody tr:hover td \{\n  background: #f1f5f9;/);
  assert.match(css, /\.gantt-row:hover \{\n  background: #f1f5f9;/);
  assert.match(cellEditorJs, /classList\.add\('cell-editing', 'choice-cell-editing'\)/);
  assert.doesNotMatch(cellEditorJs, /classList\.add\('selected-cell', 'cell-editing'\)/);
  assert.match(cellEditorJs, /const anchor = editor\.closest\('td'\) \|\| editor;[\s\S]*dropdown\.style\.width/);
  assert.match(cellEditorJs, /const dropdownHost = editor\.closest\('\.modal-backdrop'\) \|\| document\.body;/);
  assert.match(cellEditorJs, /dropdownHost\.append\(dropdown\)/);
  assert.match(css, /td\.choice-cell-editing \{[\s\S]*position: relative;[\s\S]*box-shadow: none/);
  assert.match(css, /td\.choice-cell-editing::after[\s\S]*position: absolute;[\s\S]*z-index: 10;[\s\S]*inset: 0;[\s\S]*border: 2px solid (var\(--brand\)|#2563eb);[\s\S]*pointer-events: none/);
});
